server:
  port: 18080
spring:
  application:
    name: spring-ai-alibaba-openmanus
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        enabled: false
  # MySQL database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/openmanus_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  file:
    name: ./logs/info.log
  level:
    root: INFO
